global:
  resolve_timeout: 5m
route:
  group_by: ['alertname','service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'debug'
receivers:
  - name: 'debug'
    email_configs: []
    webhook_configs:
      - url: 'http://localhost:5001/alert-receiver' # placeholder
