global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastfood-services'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:52357','localhost:52358','localhost:52360','localhost:5007','localhost:52359','localhost:52361','localhost:52362']
        labels:
          project: 'fastfood-delivery'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - "/etc/prometheus/rules/*.yml"
