---
global:
  scrape_interval: 5s  # scrape metrics every 5 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'  # scrape host metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'order-service'  # scrape order service
    static_configs:
      - targets: ['order-service:5002']  # match container port in compose

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5007']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5004']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5001']

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:5004']

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:5008']

  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant:5006']

# Add more services (payment, auth, etc.) once they expose metrics.

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rule files (drop-in alerting rules)
rule_files:
  - 'rules/test_alerts.yml'
  - 'rules/service-rules.yml'
