global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'test-exporter'
    static_configs:
      - targets: ['test-exporter:9101']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5002']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5007']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5004']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5001']

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:5004']

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:5008']

  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant:5006']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'rules/service-rules.yml'
