
global:
  scrape_interval: 5s # Quét dữ liệu mỗi 5 giây

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter' # Đo hạ tầng server
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'order-service' # Service Order của bạn
    static_configs:
      - targets: ['order-service:5002'] # Port phải khớp với container port trong docker-compose

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5007']
      
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5004']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5001']

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:5004']

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:5008']

  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant:5006']

  # Thêm các service khác (payment, auth...) tương tự khi bạn đã gắn code metrics

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rule files (drop-in alerting rules)
rule_files:
  - 'rules/test_alerts.yml'
  - 'rules/service-rules.yml'
