
global:
  scrape_interval: 5s # Quét dữ liệu mỗi 5 giây

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter' # Đo hạ tầng server
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'order-service' # Service Order của bạn
    static_configs:
      - targets: ['order-service:5002'] # Port phải khớp với container port trong docker-compose

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5007']
      
  # Thêm các service khác (payment, auth...) tương tự khi bạn đã gắn code metrics
